"""
services/exporter.py
====================
Converts narrative outputs to downloadable .md or .txt files.
"""

import io
from datetime import datetime


def to_markdown(narrative: str, repo_name: str, fmt: str) -> bytes:
    """Return narrative as UTF-8 bytes suitable for .md download."""
    header = f"<!-- Generated by Commit Story | {repo_name} | {datetime.now().strftime('%Y-%m-%d %H:%M')} -->\n\n"
    content = header + narrative
    return content.encode("utf-8")


def to_text(narrative: str, repo_name: str, fmt: str) -> bytes:
    """Return narrative as plain text UTF-8 bytes for .txt download."""
    import re
    # Strip Markdown formatting for plain text
    text = narrative
    text = re.sub(r"#{1,6}\s+", "", text)          # headings
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)   # bold
    text = re.sub(r"\*(.+?)\*", r"\1", text)        # italic
    text = re.sub(r"`(.+?)`", r"\1", text)          # inline code
    text = re.sub(r"^\s*[-*+]\s+", "• ", text, flags=re.MULTILINE)  # bullets
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)  # links
    text = re.sub(r"^\|.+\|$", "", text, flags=re.MULTILINE)  # table rows
    text = re.sub(r"\n{3,}", "\n\n", text)          # excess blank lines
    header = f"Generated by Commit Story\nRepo: {repo_name}\nFormat: {fmt}\nDate: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n{'='*60}\n\n"
    return (header + text.strip()).encode("utf-8")


def get_filename(repo_name: str, fmt: str, extension: str) -> str:
    """Generate a clean download filename."""
    safe_name = repo_name.replace("/", "-").replace(" ", "_").lower()
    date_str = datetime.now().strftime("%Y%m%d")
    return f"commit-story_{safe_name}_{fmt}_{date_str}.{extension}"
